apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel.fullname" . }}
  labels:
    {{- include "otel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: metrics
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: otpl
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: gprc
  selector:
    {{- include "otel.selectorLabels" . | nindent 4 }}
