version: "3.8"
services:
  java:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: java
    hostname: java
    image: java
    ports:
      - 8081:8081
    extra_hosts:
      - "apmserver-sample-apm-http:192.168.1.163"