version: "3.8"
services:
  java-lb:
    #image: java-lb
    build:
      context: .
      dockerfile: ./java-lb/Dockerfile
    container_name: java-lb
    environment:
      - LD_LIBRARY_PATH=/opt/opentelemetry-webserver-sdk/sdk_lib/lib
    ports:
      - "8082:8082"
  java:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: java
    hostname: java
    image: java
    ports:
      - 8081:8081
    extra_hosts:
      - "apmserver-sample-apm-http:192.168.1.163"
  collector:
    container_name: collector
    hostname: collector
    image: otel/opentelemetry-collector:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./ca.crt:/ca.crt
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    extra_hosts:
      - "apmserver-sample-apm-http:192.168.1.163"