kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-java-balancer
data:
  nginx.conf: |
    worker_processes auto;
    pid /run/nginx.pid;
    error_log  /var/log/nginx/error.log warn;
    load_module modules/ngx_otel_module.so;

    events {}
    http {
        include /etc/nginx/modules-enabled/*.conf;
        upstream java-spring {
            server nginx-apm-myappjava.myappjava.svc.cluster.local:8081;
        }
        server {
            listen 8082;

            location / {
                proxy_pass http://java-spring;
            }
        }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: opentelemetry-conf
data:
  opentelemetry_module.conf: |
    NginxModuleEnabled ON;
    NginxModuleOtelSpanExporter otlp;
    NginxModuleOtelExporterEndpoint otel.myappjava.svc.cluster.local:4317;
    NginxModuleServiceName java-lb;
    NginxModuleServiceNamespace MicroservicesMarchDemoArchitecture;
    NginxModuleServiceInstanceId DemoInstanceId;
    NginxModuleResolveBackends ON;
    NginxModuleTraceAsError ON;
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: opentelemetry-conf.template
data:
  opentelemetry_module.conf: |
    NginxModuleEnabled ON;
    NginxModuleOtelSpanExporter otlp;
    NginxModuleOtelExporterEndpoint otel.myappjava.svc.cluster.local:4317;
    NginxModuleServiceName java-lb;
    NginxModuleServiceNamespace MicroservicesMarchDemoArchitecture;
    NginxModuleServiceInstanceId ${HOSTNAME};
    NginxModuleResolveBackends ON;
    NginxModuleTraceAsError ON;