kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-java-balancer
data:
  nginx.conf: |

    events {}

    http {
        access_log  /var/log/nginx/access.log;

        upstream java-spring {
            server java:8081;
        }

        server {
            listen 8082;

            location / {
                otel_trace         on;
                otel_trace_context inject;
                proxy_pass http://java-spring;
            }
        }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: opentelemetry-conf
data:
  opentelemetry_module.conf: |
    NginxModuleEnabled ON;
    NginxModuleOtelSpanExporter otlp;
    NginxModuleOtelExporterEndpoint otel.myappjava.svc.cluster.local:4317;
    NginxModuleServiceName java-lb;
    NginxModuleServiceNamespace MicroservicesMarchDemoArchitecture;
    NginxModuleServiceInstanceId DemoInstanceId;
    NginxModuleResolveBackends ON;
    NginxModuleTraceAsError ON;
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: opentelemetry-conf.template
data:
  opentelemetry_module.conf: |
    NginxModuleEnabled ON;
    NginxModuleOtelSpanExporter otlp;
    NginxModuleOtelExporterEndpoint otel.myappjava.svc.cluster.local:4317;
    NginxModuleServiceName java-lb;
    NginxModuleServiceNamespace MicroservicesMarchDemoArchitecture;
    NginxModuleServiceInstanceId ${HOSTNAME};
    NginxModuleResolveBackends ON;
    NginxModuleTraceAsError ON;